### ISSUE TITLE
edge.ssh file needs workaround

### ISSUE THREAD

**Issue by sacretagent** [needo37/plexconnect#1]
the SSH certificate needs to stay at all costs as that needs to be the same as the one on the appletv

so when using edge=1 you 

rm -rf /opt/plexconnect
which erases that ssl certificate 

i think you need to clone to a temp location and then move everything... overwriting everything but the ssl certs
something like this
# !/bin/bash
# Does the user want the latest version

if [ -z "$EDGE" ]; then
  echo "Bleeding edge not requested"
else
  apt-get install -qy git
  cd /tmp
  git clone https://github.com/iBaa/PlexConnect.git
  cp -Rfu /tmp/PlexConnect/\* $INSTALLDIR
  rm -Rf /tmp/PlexConnect
fi
# Generate SSL certificates if they don't exist

if [ -f /opt/plexconnect/assets/certificates/trailers.pem ] ; then
  echo "SSL certs exist"
else
  openssl req -new -nodes -newkey rsa:2048 -out /opt/plexconnect/assets/certificates/trailers.pem -keyout /opt/plexconnect/assets/certificates/trailers.key -x509 -days 7300 -subj "/C=US/CN=trailers.apple.com"
  openssl x509 -in /opt/plexconnect/assets/certificates/trailers.pem -outform der -out /opt/plexconnect/assets/certificates/trailers.cer && cat /opt/plexconnect/assets/certificates/trailers.key >> /opt/plexconnect/assets/certificates/trailers.pem
fi

**Comment by needo37** [comment]
Fixed!

Thank you.
